version: '3'
services:
  mongo:
    hostname: mongo
    image: 'mvertes/alpine-mongo:latest'
    volumes:
      - ./mongodb:/data/db
    ports:
      - '27017:27017'
    restart: always
    networks:
      momenton_net:
        ipv4_address: 172.23.240.17
  momentonserver:
    hostname: momentonserver
    image: 'golra03/momentonserver:latest'
    ports:
      - '3011:3011'
    volumes:
      - './logs:/momenton/momentonserver/logs/momentonserver'
    depends_on:
      - mongo
    entrypoint:
      - /bin/sh
      - '-c'
      - >-
        set -u
        set -e
        mkdir -p ./logs/momentonserver

        DATE=`date '+%Y-%m-%d_%H-%M-%S'`

        cd /momenton/momentonserver

        npm run start:production
    environment:
      - PORT=3011
      - NODE_ENV=production
      - MONGO_HOST=172.23.240.17
      - MONGO_PORT=27017
      - MONGO_DB=momentonserver
    restart: always
    networks:
      momenton_net:
        ipv4_address: 172.23.240.12
networks:
  momenton_net:
    external: true
